<html>
<head>
	<style type="text/css" media="screen">
		@import url( '../styleSheets/layout.css' );
	</style>
	<script language="javascript" type="text/javascript" src="../main_common.js"></script>
	<script language="javascript" type="text/javascript" src="reservation.js"></script>
</head>

<body>

<script language="javascript">print_navigation_bar('reservation');</script>

<div id="reservation_ui">

<form method="post" action="https://oscars.es.net/cgi-bin/user/reservation.pl" onsubmit="return check_form(this);">

<input type="hidden" name="start_time">

<p>Please indicate the origin location and destination, along with the amount of bandwidth you would like to reserve (in Mbps).<br/>
Origin and destination locations can be either host names or IP addresses. (IPv6 is not supported yet.)</p>

<table>
	<tr>
		<th>Origin</th>
		<th>Destination</th>
		<th>Bandwidth</th>
	</tr>
	<tr>
		<td><input type="text" name="origin"></td>
		<td><input type="text" name="destination"></td>
		<td><input type="text" name="bandwidth" size="10"> Mbps</td>
	</tr>
</table>

<br/>
<p>Below, please indicate the date and time that you want to start to
use your reserved bandwidth.  The default time zone is the local<br/>
time.  The settings
shown in the Example are for two hours after the current local time.</p>

<p>The reservation start date and time must be at
least two hours later than the current date and time.<br/>
Any field left blank will default to the Example settings.</p>
<table>
	<tr>
		<th>&nbsp;</th>
		<th>year</th>
		<th>month</th>
		<th>date</th>
		<th>hour</th>
		<th>minute</th>
                <th>UTC offset</th>
	</tr>
	<tr class="alignright">
		<th>Start Time</th>
		<td><input type="text" name="start_year" size="4" maxlength="4"></td>
		<td><input type="text" name="start_month" size="2" maxlength="2"></td>
		<td><input type="text" name="start_date" size="2" maxlength="2"></td>
		<td><input type="text" name="start_hour" size="2" maxlength="2"></td>
		<td><input type="text" name="start_minute" size="2" maxlength="2"></td>
		<td><select name="start_timeoffset">
			<script language="javascript">print_timezone_offset();</script>
			<option value="+00:00">+00:00 (UTC)</option>
			<option value="+01:00">+01:00 (CET)</option>
			<option value="+02:00">+02:00 (EET)</option>
			<option value="+03:30">+03:30</option>
			<option value="+04:00">+04:00</option>
			<option value="+04:30">+04:30</option>
			<option value="+05:30">+05:30</option>
			<option value="+08:00">+08:00 (CCT)</option>
			<option value="+09:00">+09:00 (JST)</option>
			<option value="+09:30">+09:30 (ACST)</option>
			<option value="+10:00">+10:00 (GST)</option>
			<option value="+12:00">+12:00 (NZST)</option>
			<option value="-01:00">-01:00 (WAT)</option>
			<option value="-02:00">-02:00 (AT)</option>
			<option value="-03:00">-03:00</option>
			<option value="-03:30">-03:30</option>
			<option value="-04:00">-04:00 (AST)</option>
			<option value="-05:00">-05:00 (EST)</option>
			<option value="-06:00">-06:00 (CST)</option>
			<option value="-07:00">-07:00 (MST)</option>
			<option value="-08:00">-08:00 (PST)</option>
			<option value="-09:00">-09:00 (YST)</option>
			<option value="-10:00">-10:00 (AHST)</option>
			<option value="-11:00">-11:00 (NT)</option>
		</select></td>
	</tr>
	</tr>
	<tr class="alignright">
		<th>{Example}</th>
		<script language="javascript">print_start_datetime_example();</script>
	</tr>
</table>

<p>Please indicate for how long you want to reserve the bandwidth, starting from the above indicated date and time.</p>
<table>
<tr>
	<th>Duration:</th>
	<td>
		<input type="text" name="duration_hour" size="2" maxlength="2"> Hours
	</td>
</tr>
</table>

<p>Please let us know the purpose of making this reservation.</p>
<table>
<tr>
	<th>Description:</th>
	<td><textarea name="description" rows="3" cols="34"></textarea></td>
</tr>
</table>

<p><!-- Unless otherwise noted,  -->All fields except for the date and time are required for reservation. <br/>
Please check the information that you filled in, and press the [Reserve the Resource] button below.</p>

<p>
	<input type="submit" value="Reserve the Resource">
	<input type="reset" value="Reset form fields">
</p>

</form>
</div>

<script language="javascript">print_footer();</script>
</body>
</html>
