<html>
<head>
	<style type="text/css" media="screen">
		@import url( '../styleSheets/layout.css' );
	</style>
	<script language="javascript" type="text/javascript" src="../main_common.js"></script>
	<script language="javascript" type="text/javascript" src="reservation.js"></script>
</head>

<body>

<script language="javascript">print_navigation_bar('reservation');</script>

<div id="reservation_ui">

<p><em>(Please <a href="https://oscars.es.net/user/reservation.phtml">click here</a> to reload this page.)</em></p>

<form method="post" action="https://oscars.es.net/cgi-bin/user/reservation.pl" onsubmit="return check_form(this);">
<input type="hidden" name="mode" value="reserve">

<noscript>
<p class="notice">
	- <em><strong>Javascript support error</strong></em><br/>
	If you see this message, your Web browser does not support or has disabled support for Javascript.
	Please use a different Web browser or enable Javascript support in your browser.
</p>
</noscript>

<p>Please indicate the origin location and destination, along with the amount of bandwidth you would like to reserve (in Mbps).<br/>
Origin and destination locations must be IP addresses. (IPv6 is not supported yet.)</p>

<table>
	<tr>
		<th>Origin</th>
		<th>Destination</th>
		<th>Bandwidth</th>
	</tr>
	<tr>
		<td><input type="text" name="origin"></td>
		<td><input type="text" name="destination"></td>
		<td><input type="text" name="bandwidth" size="10"> Mbps</td>
	</tr>
</table>

<br/>
<p>Below, please indicate the date and time (in UTC) that you want to start to
use your reserved bandwidth.  The settings<br/>
shown in the Example are for two hours after the current time (in UTC).</p>

<p>The reservation start date and time must be at
least two hours later than the current (UTC) date and time.<br/>
Any field left blank will default to the Example settings.</p>
<table>
	<tr>
		<th>&nbsp;</th>
		<th>year</th>
		<th>month</th>
		<th>date</th>
		<th>hour</th>
		<th>minute</th>
	</tr>
	<tr class="alignright">
		<th>Start Time</th>
		<td><input type="text" name="start_year" size="4" maxlength="4"></td>
		<td><input type="text" name="start_month" size="2" maxlength="2"></td>
		<td><input type="text" name="start_date" size="2" maxlength="2"></td>
		<td><input type="text" name="start_hour" size="2" maxlength="2"></td>
		<td><input type="text" name="start_minute" size="2" maxlength="2"></td>
	</tr>
	<tr class="alignright">
		<th>{Example}</th>
		<script language="javascript">print_start_datetime_example();</script>
	</tr>
</table>

<p>Please indicate for how long you want to reserve the bandwidth, starting from the above indicated date and time.</p>
<table>
<tr>
	<th>Duration:</th>
	<td>
		<input type="text" name="duration_hour" size="2" maxlength="2"> Hours
	</td>
</tr>
</table>

<p>Please let us know the purpose of making this reservation.</p>
<table>
<tr>
	<th>Description:</th>
	<td><textarea name="description" rows="3" cols="34"></textarea></td>
</tr>
</table>

<p><!-- Unless otherwise noted,  -->All fields except for the date and time are required for reservation. <br/>
Please check the information that you filled in, and press the [Reserve the Resource] button below.</p>

<p>
	<input type="submit" value="Reserve the Resource">
	<input type="reset">
</p>

</form>
</div>

<script language="javascript">print_footer();</script>
</body>
</html>
