/*
Javascript functions for view reservation list page
Last modified: October 18, 2004
Soo-yeon Hwang (dapi@umich.edu)
*/

/* List of functions:
open_resv_detail_window( urlString )
*/

// open the reservation detailed information page in new window
// call to this function is auto-generated by the CGI program
function open_resv_detail_window( urlString )
{
	window.open( urlString,'resvdetailwindow','width=500,height=420,toolbar=no,location=no,directories=no,menubar=no,scrollbars=yes,resizable=yes' );
}
