<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<script language="javascript" type="text/javascript" src="../main_common.js"></script>
	<style type="text/css" media="screen">
		@import url( '../styleSheets/layout.css' );
	</style>
        <script language="javascript">print_html_header('user');</script>

	<script language="javascript" type="text/javascript" src="reservation.js"></script>
</head>

<body>

<script language="javascript">print_header('user');</script>

<div>
<p class="topmessage"><script language="javascript">print_current_date();</script> | You are logged in as <!-- ((_Current_LoggedIn_Name_)) -->.</p>
</div>

<script language="javascript">print_navigation_bar('reservation');</script>

<div id="reservation_ui">
<p class="notice"><!-- ((_Processing_Result_Message_)) --></p>

<p><em>(Please <a href="https://oscars.es.net/user/reservation.phtml">click here</a> to reload this page.)</em></p>

<form method="post" action="https://oscars.es.net/cgi-bin/user/reservation.pl" onsubmit="return check_form(this);">
<input type="hidden" name="mode" value="reserve">

<noscript>
<p class="notice">
	- <em><strong>Javascript support error</strong></em><br>
	If you see this message, your Web browser does not support or has disabled support for Javascript.
	Please use a different Web browser or enable Javascript support in your browser.
</p>
</noscript>

<p>Please indicate the origin location and destination, along with the amount of bandwidth you would like to reserve (in Mbps).<br>
Origin and destination locations must be IP addresses. (IPv6 is not supported yet.)</p>

<table>
	<tr>
		<th>Origin</th>
		<th>Destination</th>
		<th>Bandwidth</th>
	</tr>
	<tr>
		<td><input type="text" name="origin"></td>
		<td><input type="text" name="destination"></td>
		<td><input type="text" name="bandwidth" size="10"> Mbps</td>
	</tr>
</table>

<p>Below, please indicate the date and time that you want to start to use your reserved bandwidth.<br>
The reservation start date and time must be at least two hours later than the current date and time.
All reservations start and end on the hour.<br>
<br>
For time zone offset, the current local offset of your computer is automatically selected and is at the top of the UTC offset options list.<br>
Please select the offset based on the desired start time, also taking into consideration the 
<a href="http://www.worldtimezone.com/daylight.html" target="_blank">Daylight Saving Time</a>.</p>
<table>
	<tr>
		<th>&nbsp;</th>
		<th>Year</th>
		<th>Month</th>
		<th>Date</th>
		<th>Hour</th>
		<th>am/pm</th>
		<th><a href="http://www.worldtimezone.com/" target="_blank">Time Zone</a><br>(UTC Offset)</th>
	</tr>
	<tr class="alignright">
		<th>Start Time</th>
		<td><input type="text" name="start_year" size="4" maxlength="4"></td>
		<td><input type="text" name="start_month" size="2" maxlength="2"></td>
		<td><input type="text" name="start_date" size="2" maxlength="2"></td>
		<td><input type="text" name="start_hour" size="2" maxlength="2"></td>
		<td><select name="start_ampm">
			<option value="am">am</option>
			<option value="pm">pm</option>
		</select></td>
		<td><select name="start_timeoffset">
			<script language="javascript">print_timezone_offset();</script>
			<option value="+1400">UTC +1400</option>
			<option value="+1300">UTC +1300</option>
			<option value="+1245">UTC +1245</option>
			<option value="+1200">UTC +1200</option>
			<option value="+1130">UTC +1130</option>
			<option value="+1100">UTC +1100</option>
			<option value="+1030">UTC +1030</option>
			<option value="+1000">UTC +1000</option>
			<option value="+0930">UTC +0930</option>
			<option value="+0900">UTC +0900</option>
			<option value="+0800">UTC +0800</option>
			<option value="+0700">UTC +0700</option>
			<option value="+0630">UTC +0630</option>
			<option value="+0600">UTC +0600</option>
			<option value="+0545">UTC +0545</option>
			<option value="+0530">UTC +0530</option>
			<option value="+0500">UTC +0500</option>
			<option value="+0430">UTC +0430</option>
			<option value="+0400">UTC +0400</option>
			<option value="+0330">UTC +0330</option>
			<option value="+0300">UTC +0300</option>
			<option value="+0200">UTC +0200</option>
			<option value="+0100">UTC +0100</option>
			<option value="+0000">UTC</option>
			<option value="-0100">UTC -0100</option>
			<option value="-0200">UTC -0200</option>
			<option value="-0300">UTC -0300</option>
			<option value="-0330">UTC -0330</option>
			<option value="-0400">UTC -0400</option>
			<option value="-0500">UTC -0500</option>
			<option value="-0600">UTC -0600</option>
			<option value="-0700">UTC -0700</option>
			<option value="-0800">UTC -0800</option>
			<option value="-0900">UTC -0900</option>
			<option value="-0930">UTC -0930</option>
			<option value="-1000">UTC -1000</option>
			<option value="-1100">UTC -1100</option>
			<option value="-1200">UTC -1200</option>
		</select></td>
	</tr>
	<tr class="alignright">
		<th>{Example}</th>
		<script language="javascript">print_start_datetime_example();</script>
	</tr>
</table>

<p>Please indicate for how long you want to reserve the bandwidth, starting from the above indicated date and time.</p>
<table>
<tr>
	<th>Duration:</th>
	<td>
		<input type="text" name="duration_hour" size="2" maxlength="2"> Hours
	</td>
</tr>
</table>

<p>Please let us know the purpose of making this reservation.</p>
<table>
<tr>
	<th>Description:</th>
	<td><textarea name="description" rows="3" cols="34"></textarea></td>
</tr>
</table>

<p><!-- Unless otherwise noted,  -->All fields are required for reservation. 
Please check the information that you filled in, and press the [Reserve the Resource] button below.</p>

<p>
	<input type="submit" value="Reserve the Resource">
	<input type="reset">
</p>

</form>
</div>

<p class="copyright">(c) 2004 Internet2 BRUW Project</p>

</body>
</html>
