#!/usr/bin/perl -w

# aaas:  AAAS SOAP server.
# Last modified: October 17, 2005
# David Robertson (dwrobertson@lbl.gov)

use strict;

use SOAP::Transport::HTTP;

my %configs;

my $numArgs = $#ARGV + 1;

my $daemon = SOAP::Transport::HTTP::Daemon
  -> new (LocalPort => 2000, Listen => 5, Reuse => 1)
  -> dispatch_to('Dispatcher')
  -> handle;

######

package Dispatcher;

use Data::Dumper;
use Error qw(:try);

use Common::Exception;
use AAAS::Frontend::Validator;
use AAAS::Frontend::User;

my $aaas_user;

sub dispatch {
    my ( $class_name, $inref ) = @_;

    my( $ex,  );
    my $results = {};
    if (!$aaas_user) {
            # hard-wired
        $configs{aaas_database} = 'DBI:mysql:AAAS';
            # TODO:  use command-line options like in starting MySQL
        $configs{aaas_login} = 'oscars';
        $configs{aaas_password} = 'ritazza6';
        $aaas_user = AAAS::Frontend::User->new('configs' => \%configs);
    }

    try {
        my $v = AAAS::Frontend::Validator->new();
        my $err = $v->validate($inref);
        if ($err) { throw Common::Exception($err); }
        my $m = $inref->{method};
        $results = $aaas_user->$m($inref);
    }
    catch Common::Exception with {
        $ex = shift;
    }
    otherwise {
        $ex = shift;
    }
    finally {
        my $logfile_name = "$ENV{HOME}/logs/AAAS.err";

        open (LOGFILE, ">$logfile_name") ||
                die "Can't open log file $logfile_name.\n";
        print LOGFILE "********************\n";
        if ($ex) {
            print LOGFILE "EXCEPTION:\n";
            print LOGFILE $ex->{-text};
            print LOGFILE "\n";
        }
        close(LOGFILE);
    };
    # caught by SOAP to indicate fault
    if ($ex) {
        die SOAP::Fault->faultcode('Server')
                 ->faultstring($ex->{-text});
    }
    return $results;
}
######

######
1;
