<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<script language="javascript" type="text/javascript" src="../main_common.js"></script>
        <script language="javascript">print_html_header('user');</script>
</head>

<frameset rows="102, 42, *" border="0">
    <frame src="user/banner.html" name="banner_frame">
    <frame src="status_frame.phtml" name="status_frame">
    <frame src="login_frame.phtml" name="main_frame">
    <noframes>
        This document can only be viewed in a browser that supports frames.
    </noframes>
</frameset>
</html>
