<!DOCTYPE HTML PUBLIC "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
<link rel="stylesheet" href="styleSheets/oscars.css" type="text/css">
<title>OSCARS Login</title></head>
</head>

<body>

<table border="0" cellborder="0" width="90%">
<?php include('header.html'); ?>
  <tr>
  <td colspan="2">
  <br/>
  <br/>
  </td>
  </tr>
  <tr>
  <td align="center" colspan="2">
  OSCARS is a prototype system for handling QoS and bandwidth reservation.
  </td>
  </tr>
  <tr>
    <td colspan="2">
    <?php include('loginform.html'); ?>
    </td>
  </tr>
</table>
<?php include('footer.inc.html'); ?>

</body>
</html>
