<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<script language="javascript" type="text/javascript" src="main_common.js"></script>
	<style type="text/css" media="screen">
		@import url( './styleSheets/layout.css' );
	</style>
        <script language="javascript">print_html_header('user');</script>
</head>

<body>

<script language="javascript">print_header('user');</script>

<div>
	<p class="topmessage"><script language="javascript">print_current_date();</script> | Please sign in.</p>
</div>

<div id="login_ui">

<p><em>Please Sign In</em></p>
<p class="notice"><!-- ((_Processing_Result_Message_)) --></p>

<form method="post" action="https://oscars.es.net/cgi-bin/user/login.pl">
<input type="hidden" name="mode" value="login">

<table>
<tr>
	<th>Login Name:</th>
	<td><input type="text" name="loginname"></td>
</tr>
<tr>
	<th>Password:</th>
	<td><input type="password" name="password"></td>
</tr>
<tr>
	<th>&nbsp;</th>
	<td><input type="submit" value="Login"></td>
</tr>
</table>

</form>

<p><strong>Please <a href="./register/">click here to register</a>.</strong><br>
<br>
You need to be able to authenticate via <a href="http://shibboleth.internet2.edu/" target="_blank">Shibboleth</a> to create a new account.<br>
For inquiries, please contact the project administrator.</p>

</div>

<script language="javascript">print_footer('user');</script>
</body>
</html>
