<!DOCTYPE HTML PUBLIC "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
<link rel="stylesheet" href="styleSheets/oscars.css" type="text/css">
<title>OSCARS</title></head>
</head>

<body>

<table border="0" cellpadding="2" cellborder="0" width="90%">
<?php include('header.html'); ?>
  <tr>
    <td rowspan="3" valign="top">
<?php include('sideMenu.html'); ?>
    </td>
    <td>
<?php include('resvform.html'); ?>
    </td>
  </tr>
</table>
<?php include('footer.inc.html'); ?>

</body>
</html>
