<html>
<head>
	<script language="javascript" type="text/javascript" src="main_common.js"></script>
	<style type="text/css" media="screen">
		@import url( './styleSheets/layout.css' );
	</style>
        <script language="javascript">print_html_header('user');</script>
</head>

<body>
<div>
	<p class="topmessage"><script language="javascript">print_current_date();</script> | Please sign in.</p>
</div>

<div id="status">

<p><em>Please Sign In</em></p>
<p class="notice"><!-- ((_Processing_Result_Message_)) --></p>
</div>

</body>
</html>

