#!/bin/sh

# update classpath
OSCARS_CLASSPATH="."
for f in lib/*.jar
do
    OSCARS_CLASSPATH="$OSCARS_CLASSPATH":$f
done

for f in ../../lib/axis2/*.jar
do
    OSCARS_CLASSPATH="$OSCARS_CLASSPATH":$f
done

java -cp $OSCARS_CLASSPATH:IDCNotify.jar:. -Dcatalina.home=$CATALINA_HOME IDCNotifyServer $*

