<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title> Internet2 BRUW Project: Bandwidth Reservation for User Work </title>
	<meta http-equiv="Content-type" content="text/html; charset=iso-8859-1">
	<meta name="Author" content="Soo-yeon Hwang">
	<meta name="Keywords" content="">
	<meta name="Description" content="">

	<style type="text/css" media="screen">
		@import url( '../styleSheets/layout.css' );
	</style>

	<script language="javascript" type="text/javascript" src="./main_common.js"></script>
	<script language="javascript" type="text/javascript" src="./myprofile.js"></script>
</head>

<body>

<?php include('../header.html'); ?>

<div>
<p class="topmessage"><script language="javascript">print_current_date();</script> | You are logged in as <!-- ((_Current_LoggedIn_Name_)) -->.</p>

<ul id="tabnav">
	<li><a href="reservation.phtml" title="Create a new reservation">Make a Reservation</a></li>
	<li><a href="reservationlist.phtml" title="View list of active reservations">View Reservations</a></li>
	<li><a href="#" class="active" title="View and/or edit your personal information">My Profile</a></li>
	<li><a href="logout.phtml" title="Logout from the service">Logout</a></li>
</ul>
</div>

<div id="account_ui">

<p><em>View/Edit My Profile</em><br>
(Required fields are marked with a <span class="requiredmark">*</span>)</p>
<p class="notice"><!-- ((_Processing_Result_Message_)) --></p>

<form method="post" action="https://oscars.es.net/cgi-bin/client/myprofile.pl" onsubmit="return check_form(this);">
<input type="hidden" name="mode" value="updatemyprofile">

<table>
<tr>
	<th><span class="requiredmark">*</span> Login Name</th>
	<td><!-- ((_Current_LoggedIn_Name_)) --></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> Current Password</th>
	<td><input type="password" name="password_current" size="20"></td>
</tr>
<tr>
	<th>New Password (Enter twice; Leave blank to stay the same)</th>
	<td>
		<input type="password" name="password_new_once" size="20" style="margin-bottom: .3em"><br>
		<input type="password" name="password_new_twice" size="20">
	</td>
</tr>
</table>

<table>
<tr>
	<th><span class="requiredmark">*</span> First Name</th>
	<td><input type="text" name="firstname" size="20"></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> Last Name</th>
	<td><input type="text" name="lastname" size="20"></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> Organization</th>
	<td><input type="text" name="organization" size="40"></td>
</tr>
<tr>
	<th valign="top">Personal Description</th>
	<td><textarea name="description" rows="3" cols="34"></textarea></td>
</tr>
</table>

<table>
<tr>
	<th><span class="requiredmark">*</span> E-mail (Primary)</th>
	<td><input type="text" name="email_primary" size="40"></td>
</tr>
<tr>
	<th>E-mail (Secondary)</th>
	<td><input type="text" name="email_secondary" size="40"></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> Phone Number (Primary)</th>
	<td><input type="text" name="phone_primary" size="40"></td>
</tr>
<tr>
	<th>Phone Number (Secondary)</th>
	<td><input type="text" name="phone_secondary" size="40"></td>
</tr>
</table>

<p>Please check your contact information carefully before submitting the form.</p>

<p>
	<input type="submit" value="Change Profile">
	<input type="reset">
</p>
</form>

<p>For inquiries, please contact the project administrator.</p>

</div>

<p class="copyright">(c) 2004 Internet2 BRUW Project</p>

</body>
</html>
