#!/usr/bin/perl -w

#==============================================================================
package OSCARS::Server;

use SOAP::Transport::HTTP;

use strict;
use Data::Dumper;

use OSCARS::PluginManager;

my ( $daemon, $portnum, $authN );

# TODO:  Essentially going back to earlier version.  Need better UI.
# port number needs to be option again, config file location (or default) needs
# to be set.
my $len = scalar(@ARGV);
if ($len == 1) {
    my $firstArg = $ARGV[0];
    if ($firstArg eq '-h') {
        print STDERR "Usage:\t\toscars [portnum]\n";
        exit;
    }
    else { $portnum = $ARGV[0]; }
}
else { $portnum = 2000; }

startDaemon();

###############################################################################
#
sub startDaemon {
    my $pluginMgr = OSCARS::PluginManager->new();
    $authN = $pluginMgr->usePlugin('authentication');
    if ( !$authN ) {
        die( "Unable to find authentication plugin; does config file exist?");
    }
    $daemon = SOAP::Transport::HTTP::Daemon
        -> new (LocalPort => $portnum, Listen => 5, Reuse => 1)
        -> dispatch_to('OSCARS::Dispatcher');
    $daemon->handle;
} #____________________________________________________________________________


#==============================================================================
package OSCARS::Dispatcher;

=head1 NAME

OSCARS::Dispatcher - SOAP::Lite dispatcher for OSCARS.

=head1 SYNOPSIS

  use OSCARS::Dispatcher;

=head1 DESCRIPTION

Dispatcher for SOAP::Lite.

=head1 AUTHORS

David Robertson (dwrobertson@lbl.gov)
Mary Thompson (mrthompson@lbl.gov)

=head1 LAST MODIFIED

May 3, 2006

=cut

use Error qw(:try);
use Data::Dumper;
use SOAP::Lite;

use strict;

use OSCARS::Logger;
use OSCARS::Method;

# intermediate step to different style of dispatching; this is not the final 
# version

### publicly available methods

###############################################################################
#
sub userLogin {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub userLogout {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub userQuery {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub userModify {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub institutionList {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub queryReservation {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub createReservation {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub modifyReservation {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub cancelReservation {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub listReservations {
    my( $className, $params ) = @_;

    return handle($params);
}

### internal methods

###############################################################################
#
sub userAdd {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub userRemove {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub userList {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub permissionList {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub resourceList {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub authorizationList {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub reservationPending {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub reservationExpired {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub topologyUpdate {
    my( $className, $params ) = @_;

    return handle($params);
}

# public Interdomain (currently in Intradomain)

###############################################################################
#
sub forward {
    my( $className, $params ) = @_;

    return handle($params);
}

###############################################################################
#
sub handle {
    my( $params ) = @_;

    my $ex;
    my( $user, $handler, $som );

    my $logger = OSCARS::Logger->new('method' => $params->{method});
    $logger->set_level($NetLogger::INFO);
    if ( $params->{login} ) {
        $logger->setUserLogin($params->{login});
    }
    $logger->open('/home/oscars/logs/oscars.log');
    my $results = {};
    try {
        $user = $authN->authenticate($daemon, $params);
	$logger->setUserLogin($user->{login});
        my $factory = OSCARS::MethodFactory->new();
        $handler = $factory->instantiate( $user, $params, $logger );
        # Handles SOAP method.  Handler may make other SOAP calls to
	# accomplish its task.
        $results = $handler->soapMethod();
    }
    catch Error::Simple with { $ex = shift; }
    otherwise { $ex = shift; }
    finally {
        if ($ex) {
            print STDERR $ex->{-text}, "\n";
            $logger->warning("exception: $ex->{-text}", $params);
	    $logger->close();
                # caught by SOAP to indicate fault
            die SOAP::Fault->faultcode('Server')
                 ->faultstring($ex->{-text});
        }
        elsif ($handler) { $handler->postProcess($results); }
        if ($params->{method} eq 'userLogout') {
            $authN->removeUser($params->{login});
        }
        $logger->close();
    };
    return $results;
} #____________________________________________________________________________


######
1;
