#!/usr/bin/perl -w

#==============================================================================
package OSCARS::Server;

use SOAP::Transport::HTTP;
use Getopt::Std;

use strict;
use Data::Dumper;

use OSCARS::PluginManager;
use OSCARS::MethodFactory;

my ( $daemon, $factory, $authN );

my $usage ="oscars [-p portnum] [-c configFile] [-h]\n";
my $portnum = 2000;
my $configFile = "$ENV{HOME}/.oscars.xml";

my %opts;

getopt('pch', \%opts);
if (exists $opts{h} ) {
    print STDERR "Usage: $usage\n";
    exit; 
}
if (defined $opts{p} ) { $portnum = $opts{p}; }
if (defined $opts{c} ) { $configFile = $opts{c}; }

startDaemon();

###############################################################################
#
sub startDaemon {
    my $pluginMgr = OSCARS::PluginManager->new('location' => $configFile);
    $authN = $pluginMgr->usePlugin('authentication');
    if ( !$authN ) {
        die( "Unable to find authentication plugin; does config file exist?");
    }
    $factory = OSCARS::MethodFactory->new('pluginMgr' => $pluginMgr);
    $daemon = SOAP::Transport::HTTP::Daemon
        -> new (LocalPort => $portnum, Listen => 5, Reuse => 1)
        -> dispatch_to('OSCARS::Dispatcher');
    print "contact server at oscars-dev.es.net:2001\n";
    $daemon->handle;
} #____________________________________________________________________________


#==============================================================================
package OSCARS::Dispatcher;

=head1 NAME

OSCARS::Dispatcher - SOAP::Lite dispatcher for OSCARS.

=head1 SYNOPSIS

  use OSCARS::Dispatcher;

=head1 DESCRIPTION

Dispatcher for SOAP::Lite.

=head1 AUTHORS

David Robertson (dwrobertson@lbl.gov)
Mary Thompson (mrthompson@lbl.gov)

=head1 LAST MODIFIED

July 3, 2006

=cut

use Error qw(:try);
use Data::Dumper;
use SOAP::Lite;

use strict;

use OSCARS::Logger;
use OSCARS::Method;
use OSCARS::Library::Serializer;

# NOTE:  Extra enclosing types are to satisfy clients that used WSDL to
#        generate stubs (no Perl generator works for complexTypes yet).

### publicly available methods

###############################################################################
#
sub userLogin {
    my( $className, $request ) = @_;

    my $results = handle($request, 'userLogin');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub userLogout {
    my( $className, $request ) = @_;

    my $results = handle($request, 'userLogout');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub userQuery {
    my( $className, $request ) = @_;

    my $results = handle($request, 'userQuery');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub userModify {
    my( $className, $request ) = @_;

    my $results = handle($request, 'userModify');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub institutionList {
    my( $className, $request ) = @_;

    my $results = handle($request, 'institutionList');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub queryReservation {
    my( $className, $request ) = @_;

    my $results = handle($request, 'queryReservation');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
	->value($results);
#        ->value(OSCARS::Library::Serializer::serializeQueryResReply($results));
    return $response;
}

###############################################################################
#
sub createReservation {
    my( $className, $request ) = @_;

    my $results = handle($request, 'createReservation');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub modifyReservation {
    my( $className, $request ) = @_;

    my $results = handle($request, 'modifyReservation');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub cancelReservation {
    my( $className, $request ) = @_;

    my $results = handle($request, 'cancelReservation');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub listReservations {
    my( $className, $request ) = @_;

    my $results = handle($request, 'listReservations');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

### internal methods

###############################################################################
#
sub userAdd {
    my( $className, $request ) = @_;

    my $results = handle($request, 'userAdd');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub userRemove {
    my( $className, $request ) = @_;

    my $results = handle($request, 'userRemove');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub userList {
    my( $className, $request ) = @_;

    my $results = handle($request, 'userList');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub permissionList {
    my( $className, $request ) = @_;

    my $results = handle($request, 'permissionList');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub resourceList {
    my( $className, $request ) = @_;

    my $results = handle($request, 'resourceList');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub authorizationList {
    my( $className, $request ) = @_;

    my $results = handle($request, 'authorizationList');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub reservationPending {
    my( $className, $request ) = @_;

    my $results = handle($request, 'reservationPending');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub reservationExpired {
    my( $className, $request ) = @_;

    my $results = handle($request, 'reservationExpired');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

###############################################################################
#
sub topologyUpdate {
    my( $className, $request ) = @_;

    my $results = handle($request, 'topologyUpdate');
    my $response = SOAP::Data
        ->uri('http://oscars.es.net/OSCARS/Dispatcher')
        ->value($results);
    return $response;
}

# public Interdomain (currently in Intradomain)

###############################################################################
#
sub forward {
    my( $className, $request ) = @_;

    my $results = handle($request, 'forward');
    my $response = OSCARS::Library::Serializer::serializeForwardReply($results);
    
    return $response;
}

###############################################################################
#  Test for use with BNL.
sub testForward {
    my( $className, $payload, $payloadSender, $userLogin ) = @_;
    my $request = $payload;
    $request->{userLogin} = {};
    $request->{userLogin}->{userName} = $userLogin->{userName};
    $request->{userLogin}->{password} = $userLogin->{password};
    $request->{payloadSender}= $payloadSender;
    print "in oscars - testForward request\n", Dumper($request);
    my $results = handle($request, 'testForward');
    #print "in oscars testForward results are:\n";
    #print Dumper ($results); 
   print "payloadContentType is $payload->{contentType}\n";
    my $response =  OSCARS::Library::Serializer::serializeForwardReply(
		$payload->{contentType},$results);
    return $response;
}

###############################################################################
#
sub handle {
    my( $request, $method ) = @_;

    my $ex;
    my( $user, $handler, $som );

     # this occurs if there are no input parameters
    if (!$request) { $request = {}; }
    $request->{method} = $method;
    my $logger = OSCARS::Logger->new('method' => $method);
    $logger->set_level($NetLogger::INFO);
    $logger->open('/home/oscars/mrtlogs/oscars.log');
    my $results = {};
    try {
        $user = $authN->authenticate($daemon, $request);
        $logger->setUserLogin($user->{login});
        $handler = $factory->instantiate( $user, $method );
        # Handles SOAP method.  Handler may make other SOAP calls to
        # accomplish its task.
        $results = $handler->soapMethod($request, $logger);
    }
    catch Error::Simple with { $ex = shift; }
    otherwise { $ex = shift; }
    finally {
        if ($ex) {
            print STDERR $ex->{-text}, "\n";
            $logger->warning("exception: $ex->{-text}", $request);
            $logger->close();
                # caught by SOAP to indicate fault
            die SOAP::Fault->faultcode('Server')
                 ->faultstring($ex->{-text});
        }
        elsif ($handler) { $handler->postProcess($request, $results); }
        if ($method eq 'userLogout') {
            $authN->removeUser($request->{login});
        }
        $logger->close();
    };
    return $results;
} #____________________________________________________________________________


######
1;
