localdomain: mydomain.net
db_user: MYUSER
db_pass: MYPASS
#edge_ports:
#    - label: "MyNode->host1"
#      urn : "urn:ogf:network:domain=mydomain.net:node=MyNode:port=1:link=*"
#    - label: "MyNode->host2"
#      urn : "urn:ogf:network:domain=mydomain.net:node=MyNode:port=2:link=*"
#exclude_links:
#     MyNode1->MyNode2 : 1