DROP TABLE  users
DROP TABLE  institutions
DROP TABLE  resources
DROP TABLE  permissions
DROP TABLE  resourcePermissions
DROP TABLE  authorizations
DROP TABLE  clients
DROP TABLE  domains
DROP TABLE  hosts
DROP TABLE  reservations
DROP TABLE  archivedReservations
