#!/bin/sh

# update classpath
OSCARS_CLASSPATH="."
for f in lib/*.jar
do
    OSCARS_CLASSPATH="$OSCARS_CLASSPATH":$f
done

java -Djava.net.preferIPv4Stack=true -cp $OSCARS_CLASSPATH:IDCUtil.jar IDCOrgUtil add $*
