#!/bin/bash
###############################################################################
# USAGE: idc-kspasswd
# 
# Changes the keystore passwords of sec-server.jks and sec-client.jks and stores
# the changes in their associated .properties files.
###############################################################################
REPO_PATH=""
if [ -n "$OSCARS_HOME" ]; then
	REPO_PATH="$OSCARS_HOME/conf/axis-tomcat"
elif [ -n "$CATALINA_HOME" ]; then
	REPO_PATH="$CATALINA_HOME/shared/classes/repo"
elif [ -d "./conf/axis-tomcat" ]; then
	REPO_PATH="./conf/axis-tomcat"
elif [ -d "./repo" ]; then
	REPO_PATH="./repo"
else
    echo "ERROR: Unable to find keystore."
    exit 1
fi

KS_PATH="$REPO_PATH/OSCARS.jks";
RAMP_CONF="$REPO_PATH/rampConfig.xml";

while [ 1 ]; do
    OLD_PASSWD="";
    printf "Enter the old keystore password: "
    stty -echo;
    read OLD_PASSWD;
    stty echo;
    echo "";
    
    NEW_PASSWD="";
    printf "Enter the new keystore password: "
    stty -echo;
    read NEW_PASSWD;
    stty echo;
    echo "";
    
    NEW_PASSWD2="";
    printf "Re-enter the new keystore password: "
    stty -echo;
    read NEW_PASSWD2;
    stty echo;
    echo "";
    
    if [ "$NEW_PASSWD" != "" ] && [ "$NEW_PASSWD2" != "" ] && [ "$NEW_PASSWD" == "$NEW_PASSWD2" ]; then
        keytool -storepasswd -keystore $KS_PATH -new $NEW_PASSWD -storepass $OLD_PASSWD
    else
        echo "-- New password fields do not match. Please try again...";
        continue;
    fi
    
    if [ $? != 0 ]; then 
        echo "-- Keytool returned an error when changing the password. Please try again...";
        continue;
    fi
    
    sed -i -e "s/<ramp:property name=\"org\.apache\.ws\.security\.crypto\.merlin\.keystore\.password\">.*<\/ramp:property>/<ramp:property name=\"org.apache.ws.security.crypto.merlin.keystore.password\">$NEW_PASSWD<\/ramp:property>/" $RAMP_CONF;
    if [ $? != 0 ]; then 
        echo "-- Sed returned an error when updating '$RAMP_CONF'. Please manually change the field org.apache.ws.security.crypto.merlin.keystore.password=YOUR_NEW_PASSWORD in $RAMP_CONF to your new password.";
        exit;
    fi
    
    echo "-- Password changed";
    exit 0;
done