#!/bin/bash
###############################################################################
# USAGE: idc-certexport
# 
# Exports a certificate to a file from a chosen keystore
###############################################################################

if [ -z "$CATALINA_HOME" ]; then
	echo "Required environment variable CATALINA_HOME is not set. Please run do_build.sh .";
	exit 1;
fi

KS_PATH="";
KS_PASS="";
REPO_PATH="$CATALINA_HOME/shared/classes/repo";

while [ 1 ]; do
    echo "Choose the keystore with the certificate you'd like to export:";
    echo "    1. OSCARS.jks - stores the private key for sending and public key for receiving messages from other IDCs";
    echo "    2. ssl-keystore.jks - stores SSL certificates of other IDCs running HTTPS";
    
    printf "Enter choice: ";
    read OPCHOICE;
    
    if [ "$OPCHOICE" == "1" ]; then
        KS_PATH="$REPO_PATH/OSCARS";
        break;
    elif [ "$OPCHOICE" == "2" ]; then
        KS_PATH="$REPO_PATH/ssl-keystore";
        KS_PASS="oscars";
        break;
    else
       echo "Invalid choice. Please choose 1, 2, or 3."; 
    fi
done

if [ -z "$KS_PASS" ]; then 
    KS_PASS=`grep "org.apache.ws.security.crypto.merlin.keystore.password" $REPO_PATH/rampConfig.xml | sed -e 's/\s*<ramp:property name="org\.apache\.ws\.security\.crypto\.merlin\.keystore\.password">\(.*\)<\/ramp:property>/\1/'`;
    if [ $? != 0 ]; then
        echo "-- Error while trying to determine keystore password. Please check error message above and try running idc-certadd again.";
        exit 1;
    fi
fi

CERT_ALIAS="";
CERT_LIST=`keytool -list -keystore $KS_PATH.jks -storepass $KS_PASS | grep "Entry" | sed -e "s/\([a-zA-Z0-9_-]*\),.*/\1/g"`;
if [ $? != 0 ]; then
    echo "-- Error while trying to list certificates in the keystore. Please manually enter the alias of the certificate you'd like to export";
    echo "";
    printf "Enter certificate alias: ";
    read CERT_ALIAS;
fi

CERTS=( );
while [ -z "$CERT_ALIAS" ]; do
    CERTS=( );
    COUNT=0;
    echo "";
    echo "Choose the certificate you wish to export:"
    for LINE in $( echo "$CERT_LIST" ); do
        COUNT=`expr $COUNT + 1`;
        echo "    $COUNT. $LINE";
        CERTS[`expr $COUNT - 1`]="$LINE";
    done
    printf "Enter choice: ";
    read OPCHOICE;

    if [ -z "$OPCHOICE" ] || [ -z `echo $OPCHOICE | egrep "^[0-9]+$"` ] || [ $OPCHOICE -lt 1 ] || [ $OPCHOICE -gt $COUNT ]; then
        echo "Invalid choice. Please choose a value between 1 and $COUNT."; 
        continue;
    fi

    OPCHOICE=`expr $OPCHOICE - 1`;
    CERT_ALIAS=${CERTS[$OPCHOICE]};
done

CERT_FILE="";
printf "What filename should I give the exported certificate?: ";
read CERT_FILE;

keytool -export -keystore $KS_PATH.jks -alias $CERT_ALIAS -storepass $KS_PASS -rfc -file $CERT_FILE;
if [ $? != 0 ]; then
    echo "-- Keytool returned an error. Your certificate was not exported.";
    exit 1;
fi

echo "-- Certificate successfully exported";
exit 0;
