#!/bin/bash
###############################################################################
# USAGE: idc-certview
# 
# Displays a certificate from a chosen keystore
###############################################################################

if [ -z "$CATALINA_HOME" ]; then
	echo "Required environment variable CATALINA_HOME is not set. Please run do_build.sh .";
	exit 1;
fi

KS_PATH="";
KS_PASS="";
REPO_PATH="$CATALINA_HOME/shared/classes/repo";

print_cert ()
{
    CERTFILE="";
    while [ 1 ]; do
        printf "Enter the certificate filename: ";
        read CERTFILE;
        if [ -f "$CERTFILE" ]; then
            break;
        else
            echo "- Cannot find certificate file '$CERTFILE'"; 
        fi
    done
    
    echo "-- Certificate Details";
    echo "--- NOTE: The 'Owner' field is the X.509 subject name";
    echo "";
    keytool -printcert -V -file $CERTFILE;
    if [ $? != 0 ]; then
        echo "-- Error printing certificate.";
        exit 1;
    fi
}

while [ 1 ]; do
    echo "Choose the keystore or file with the certificate you'd like to view:";
    echo "    1. OSCARS.jks - stores the private key for sending and public key for receiving messages from other IDCs";
    echo "    2. ssl-keystore.jks - stores SSL certificates of other IDCs running HTTPS";
    echo "    3. Open certificate file...";
    
    printf "Enter choice: ";
    read OPCHOICE;
    
    if [ "$OPCHOICE" == "1" ]; then
        KS_PATH="$REPO_PATH/OSCARS";
        break;
    elif [ "$OPCHOICE" == "2" ]; then
        KS_PATH="$REPO_PATH/ssl-keystore";
        KS_PASS="oscars";
        break;
    elif [ "$OPCHOICE" == "3" ]; then
        print_cert "";
        exit 0;
    else
       echo "Invalid choice. Please choose 1, 2, or 3."; 
    fi
done

if [ -z "$KS_PASS" ]; then 
    KS_PASS=`grep "org.apache.ws.security.crypto.merlin.keystore.password" $REPO_PATH/rampConfig.xml | sed -e 's/\s*<ramp:property name="org\.apache\.ws\.security\.crypto\.merlin\.keystore\.password">\(.*\)<\/ramp:property>/\1/'`;
    if [ $? != 0 ]; then
        echo "-- Error while trying to determine keystore password. Please check error message above and try running idc-certadd again.";
        exit 1;
    fi
fi

CERT_ALIAS="";
CERT_LIST=`keytool -list -keystore $KS_PATH.jks -storepass $KS_PASS | grep "Entry" | sed -e "s/\([a-zA-Z0-9_-]*\),.*/\1/g"`;
if [ $? != 0 ]; then
    echo "-- Error while trying to list certificates in the keystore. Please manually enter the alias of the certificate you'd like to view";
    echo "";
    printf "Enter certificate alias: ";
    read CERT_ALIAS;
fi

CERTS=( );
while [ -z "$CERT_ALIAS" ]; do
    CERTS=( );
    COUNT=0;
    echo "";
    echo "Choose the certificate you wish to view:"
    for LINE in $( echo "$CERT_LIST" ); do
        COUNT=`expr $COUNT + 1`;
        echo "    $COUNT. $LINE";
        CERTS[`expr $COUNT - 1`]="$LINE";
    done
    printf "Enter choice: ";
    read OPCHOICE;

    if [ -z "$OPCHOICE" ] || [ -z `echo $OPCHOICE | egrep "^[0-9]+$"` ] || [ $OPCHOICE -lt 1 ] || [ $OPCHOICE -gt $COUNT ]; then
        echo "Invalid choice. Please choose a value between 1 and $COUNT."; 
        continue;
    fi

    OPCHOICE=`expr $OPCHOICE - 1`;
    CERT_ALIAS=${CERTS[$OPCHOICE]};
done

echo "";
echo "-- Certificate details"
echo "";
keytool -list -keystore $KS_PATH.jks -storepass $KS_PASS -alias $CERT_ALIAS -V

exit 0;



