<html>
<head>
<style type="text/css">
.oscheader {font-family:sans-serif,helvetica,arial,serif}
.oscheader {font-size:large;font-weight:bold}
.oscheader {color:white;background-color:#0961cb}
td {font-family: sans-serif,serif;font-size:medium}
th {font-weight:bold;font-family: sans-serif,serif;font-size:medium}
th {background-color:navy;color:white;text-align:left}
th A:link {color:yellow}
th A:visited {color:lightblue}
</style><title>OSCARS Login</title></head>

<body bgcolor="white">
<table border="0" cellpadding="6" cellborder="0" width="100%">
<tr>
<td>
<a href="http://www.es.net">
<img border="0" width="77" height="58" align="middle" src="ESnetLogo.png">
</td>
<td class="oscheader" valign="center">
On-demand Secure Circuits and Advanced Reservations System (OSCARS)
</td></tr></table>

<p>
<font color="red" size="+1">
</font>
<!--**  login.phtml  **-->
<!--**Text in this file gets inserted at the top of the NIM login page **-->
</p><p>
</p>
<!-- <form action="auth.php" method="post" name="nimlogin">
-->
<center>
<table bgcolor="grey" border="1"><tr><td>
<table border="0" cellpadding="2" cellspacing="0">

<tr bgcolor="lightgrey">
<td align="right">
<strong>OSCARS Username:</strong></td><td> <input name="username" maxlength="30" type="text">
</td></tr>
<tr bgcolor="lightgrey">
<td align="right">
<strong>OSCARS Password:</strong></td><td> <input name="password" maxlength="30" type="password">

</td></tr></table></td></tr></table>

</center><br>

<center>
<!--<INPUT TYPE=image NAME="Submit" VALUE="Submit" src="gifs/signon.gif" border=0> -->
<input name="Submit" value="Log In" border="0" type="submit">

</center>

</form>

<!--#include file="footer.inc.html" -->

</body>
</html>
