nsi clear
verbose off
resv load --name myresv
resv set --st "10 sec" --et "30 min"
resv set --sv 1781 --dv 1781
resv show

nsi reserve
nsi wait --type "RESERVE_CONFIRMED"
nsi commit
nsi wait --type "COMMIT_CONFIRMED"
nsi provision
nsi wait --type "PROVISION_CONFIRMED"

sleep --sec 30

// modify
resv set --b 2
nsi reserve
nsi wait --type "RESERVE_CONFIRMED"
nsi commit
nsi wait --type "COMMIT_CONFIRMED"

sleep --sec 30
nsi terminate
verbose on