<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title> Internet2 BRUW Project: Admin Tool </title>
	<meta http-equiv="Content-type" content="text/html; charset=iso-8859-1">
	<meta name="Author" content="Soo-yeon Hwang">
	<meta name="Keywords" content="">
	<meta name="Description" content="">

	<style type="text/css" media="screen">
		@import url( '../styleSheets/layout.css' );
	</style>

	<script language="javascript" type="text/javascript" src="../main_common.js"></script>
	<script language="javascript" type="text/javascript" src="adduser.js"></script>
</head>

<body>

<?php include('adminheader.html'); ?>

<div>
<p class="topmessage"><script language="javascript">print_current_date();</script> | Admin Tool | You are logged in as <!-- ((_Current_LoggedIn_Name_)) -->.</p>
</div>

<script language="javascript">print_admin_bar('adduser');</script>

<div id="account_ui">

<p><em>Add a New User Account</em><br>
(Required fields are marked with a <span class="requiredmark">*</span>)</p>
<p>Users can register themselves, or you can manually create a user account here.<br>
A manually registered user will receive an email with activation key and other login information.</p>

<p class="notice"><!-- ((_Processing_Result_Message_)) --></p>

<form method="post" action="https://oscars.es.net/cgi-bin/admin/adduser.phtml" name="adduserform" onsubmit="return check_form(this);">
<input type="hidden" name="mode" value="adminadduser">

<table>
<tr>
	<th><span class="requiredmark">*</span> Login Name</th>
	<td><input type="text" name="loginname" size="16"> &nbsp;<input type="button" value="Overlap Check" onClick="login_name_overlap_check(document.adduserform.loginname);"></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> Password (Enter twice)</th>
	<td>
		<input type="password" name="password_once" size="20" style="margin-bottom: .3em"><br>
		<input type="password" name="password_twice" size="20">
	</td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> User Level</th>
	<td>
		<select name="level">
			<option value="1">Lv 1: [User] Granted all user privileges</option>
			<option value="2">Lv 2: [User] Granted read privilege only</option>
			<option value="10">Lv 10: [Admin] Granted all user/admin privileges</option>
		</select>
	</td>
</tr>
</table>

<table>
<tr>
	<th><span class="requiredmark">*</span> First Name</th>
	<td><input type="text" name="firstname" size="20"></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> Last Name</th>
	<td><input type="text" name="lastname" size="20"></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> Organization</th>
	<td><input type="text" name="organization" size="40"></td>
</tr>
<tr>
	<th valign="top">Personal Description</th>
	<td><textarea name="description" rows="3" cols="34"></textarea></td>
</tr>
</table>

<table>
<tr>
	<th><span class="requiredmark">*</span> E-mail (Primary)</th>
	<td><input type="text" name="email_primary" size="40"></td>
</tr>
<tr>
	<th>E-mail (Secondary)</th>
	<td><input type="text" name="email_secondary" size="40"></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> Phone Number (Primary)</th>
	<td><input type="text" name="phone_primary" size="40"></td>
</tr>
<tr>
	<th>Phone Number (Secondary)</th>
	<td><input type="text" name="phone_secondary" size="40"></td>
</tr>
</table>

<p>
	<input type="submit" value=" Register ">
	<input type="reset">
</p>
</form>

<p>For inquiries, please contact the project administrator.</p>

</div>

<p class="copyright">(c) 2004 Internet2 BRUW Project</p>

</body>
</html>
