<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<script language="javascript" type="text/javascript" src="../main_common.js"></script>
	<style type="text/css" media="screen">
		@import url( '../styleSheets/layout.css' );
	</style>
        <script language="javascript">print_html_header('admin');</script>
</head>

<body>

<script language="javascript">print_header('admin');</script>

<div>
	<p class="topmessage"><script language="javascript">print_current_date();</script> | Admin Tool</p>
</div>

<div id="account_ui">

<p><!-- ((_Processing_Result_Message_)) --></p>

</div>

</body>
</html>
