<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title> Internet2 BRUW Project: Admin Tool </title>
	<meta http-equiv="Content-type" content="text/html; charset=iso-8859-1">
	<meta name="Author" content="Soo-yeon Hwang">
	<meta name="Keywords" content="">
	<meta name="Description" content="">

	<style type="text/css" media="screen">
		@import url( '../styleSheets/layout.css' );
	</style>

	<script language="javascript" type="text/javascript" src="../main_common.js"></script>
</head>

<body>

<script language="javascript">print_header('admin');</script>

<div>
	<p class="topmessage"><script language="javascript">print_current_date();</script> | Admin Tool</p>
</div>

<div id="account_ui">

<p><!-- ((_Processing_Result_Message_)) --></p>

</div>

</body>
</html>
