<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<script language="javascript" type="text/javascript" src="../main_common.js"></script>
	<style type="text/css" media="screen">
		@import url( '../styleSheets/layout.css' );
	</style>
        <script language="javascript">print_html_header('admin');</script>
	<script language="javascript" type="text/javascript" src="userlist.js"></script>
</head>

<body>

<script language="javascript">print_header('admin');</script>

<div>
<p class="topmessage"><script language="javascript">print_current_date();</script> | Admin Tool | You are logged in as <!-- ((_Current_LoggedIn_Name_)) -->.</p>

<ul id="tabnav">
	<li><a href="userlist.phtml" class="active" title="View and/or edit user accounts">Edit User Accounts</a></li>
	<li><a href="adduser.phtml" title="Add a new user account">Add a New User</a></li>
	<li><a href="editprofile.phtml"" title="View and/or edit admin profile">Admin Profile</a></li>
	<li><a href="logout.phtml" title="Logout from the admin tool">Logout</a></li>
</ul>
</div>

<div id="account_ui">

<p><em>View/Edit User Profile</em><br>
(Required fields are marked with a <span class="requiredmark">*</span>)</p>
<p class="notice"><!-- ((_Processing_Result_Message_)) --></p>

<form method="post" action="https://oscars.es.net/cgi-bin/admin/userlist.pl" onsubmit="return check_update_form(this);">
<input type="hidden" name="mode" value="useraccupdate">

<p><input type="button" value="Return to the User List without Making Changes" onclick="document.location=location.href.replace( /\?.*$/, '' );"></p>

<table>
<tr>
	<th><span class="requiredmark">*</span> Login Name</th>
	<td><!-- ((_User_Login_Name_)) --><input type="hidden" name="loginname"></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> User Level</th>
	<td>
		<select name="level">
			<option value="0">Lv 0: [User] Admin authorization is required</option>
			<option value="1">Lv 1: [User] Granted all user privileges</option>
			<option value="2">Lv 2: [User] Granted read privilege only</option>
			<option value="10">Lv 10: [Admin] Granted all user/admin privileges</option>
		</select>
	</td>
</tr>
<tr>
	<th>Registered Since</th>
	<td><!-- ((_Registration_Date_)) --></td>
</tr>
</table>

<table>
<tr>
	<th><span class="requiredmark">*</span> First Name</th>
	<td><input type="text" name="firstname" size="20"></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> Last Name</th>
	<td><input type="text" name="lastname" size="20"></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> Organization</th>
	<td><input type="text" name="organization" size="40"></td>
</tr>
<tr>
	<th valign="top">Personal Description</th>
	<td><textarea name="description" rows="3" cols="34"></textarea></td>
</tr>
</table>

<table>
<tr>
	<th><span class="requiredmark">*</span> E-mail (Primary)</th>
	<td><input type="text" name="email_primary" size="40"></td>
</tr>
<tr>
	<th>E-mail (Secondary)</th>
	<td><input type="text" name="email_secondary" size="40"></td>
</tr>
<tr>
	<th><span class="requiredmark">*</span> Phone Number (Primary)</th>
	<td><input type="text" name="phone_primary" size="40"></td>
</tr>
<tr>
	<th>Phone Number (Secondary)</th>
	<td><input type="text" name="phone_secondary" size="40"></td>
</tr>
</table>

<p>
	<input type="submit" value="Update User Profile">
	<input type="reset">
</p>
</form>

<!-- ((_Password_Reset_Form_Begin_)) -->
<table class="emphasis_bg1">
<tr>
	<td align="center">
		<p>
		<strong>To reset this user's password, please type it below and submit it.</strong><br>
		This action cannot be undone, so please be careful in doing so.<br>
		The user will receive the changed password in email.<br>
		</p>
		<form method="post" action="https://oscars.es.net/cgi-bin/admin/userlist.pl" onsubmit="return confirm_password_reset(this);">
			<input type="hidden" name="mode" value="userpasswdreset">
			<input type="hidden" name="loginname">
			<input type="text" name="password_new" size="20">
			<input type="submit" value="Reset Password">
		</form>
	</td>
</tr>
</table>
<!-- ((_Password_Reset_Form_End_)) -->

<!-- ((_Account_Delete_Form_Begin_)) -->
<table class="emphasis_bg2">
<tr>
	<td align="center">
		<p>
		<strong>To delete this user account, please click the button below.</strong><br>
		This action cannot be undone, so please be careful in doing so.<br>
		</p>
		<form method="post" action="https://oscars.es.net/cgi-bin/admin/userlist.pl" onsubmit="return confirm_account_delete(this);">
			<input type="hidden" name="mode" value="useraccdelete">
			<input type="hidden" name="loginname">
			<input type="submit" value="Delete This User Account">
		</form>
		<p>Along with the account, all the reservations made by the user will be deleted as well.</p>
	</td>
</tr>
</table>
<!-- ((_Account_Delete_Form_End_)) -->

<p>For inquiries, please contact the project administrator.</p>

</div>

</body>
</html>
