<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title> Internet2 BRUW Project: Admin Tool </title>
	<meta http-equiv="Content-type" content="text/html; charset=iso-8859-1">
	<meta name="Author" content="Soo-yeon Hwang">
	<meta name="Keywords" content="">
	<meta name="Description" content="">

	<style type="text/css" media="screen">
		@import url( '../styleSheets/layout.css' );
	</style>

	<script language="javascript" type="text/javascript" src="../client/main_common.js"></script>
</head>

<body onload="stripe('userlist', '#fff', '#edf3fe');">

<?php include('adminheader.html'); ?>

<div>
<p class="topmessage"><script language="javascript">print_current_date();</script> | Admin Tool | You are logged in as <!-- ((_Current_LoggedIn_Name_)) -->.</p>
</div>

<?php include('navbar.html'); ?>

<div id="zebratable_ui">

<p><em>View/Edit User Accounts</em><br>
<p>Click the Login Name link to view the user's detailed account information<br>
and make changes to it, including authorizing a newly registered account.</p>

<p class="notice"><!-- ((_Processing_Result_Message_)) --></p>

<table cellspacing="0" id="userlist">
	<thead>
		<tr>
			<td>Registration ID #</td>
			<td>Login Name</td>
			<td>First Name</td>
			<td>Last Name</td>
			<td>Primary E-mail Address</td>
			<td>User Level</td>
		</tr>
	</thead>
	<tbody>
	<!-- ((_User_List_)) -->
	</tbody>
</table>

<p>For inquiries, please contact the project administrator.</p>

</div>

</body>
</html>
