<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<script language="javascript" type="text/javascript" src="https://oscars.es.net/main_common.js"></script>
        <script language="javascript">print_html_header('user');</script>
</head>

<frameset rows="10%, 6%, *" border="0">
    <frame src="../user/banner.html" name="banner_frame">
    <frame src="../status_frame.html" name="status_frame">
    <frame src="people.html" name="main_frame">
    <noframes>
        This document can only be viewed in a browser that supports frames.
    </noframes>
</frameset>
</html>
