<!DOCTYPE HTML PUBLIC "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
<link rel="stylesheet" href="../styleSheets/oscars.css" type="text/css">
<title>OSCARS</title></head>
</head>

<body>

<table border="0" cellpadding="2" cellborder="0" width="90%">
<?php include('../header.html'); ?>
  <tr>
    <td rowspan="3" valign="top">
<?php include('../sideMenu.html'); ?>
    </td>
    <td>
<h2>OSCARS Project Participants</h2>
<ul>
<li>
Chin Guok is the principal investigator of the OSCARS project .<br/><br/>

<li><a href="http://dsd.lbl.gov/~davidr">David Robertson</a> is a software
engineer developing the reservation manager component of OSCARS.<br/><br/>
</ul>
    </td>
  </tr>
</table>
<?php include('../footer.inc.html'); ?>

</body>
</html>
